version: '3.7'

networks:
  local-machinedata:

volumes:
  postgres-local-data:
  grafana-data:

services:
  postgres:
    image: postgres:14.5
    container_name: postgres_db
    ports:
      - 5432:5432
    networks:
      - local-machinedata
    volumes:
      - type: volume
        source: postgres-local-data
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd

  jaeger:
    image: jaegertracing/all-in-one:1.38
    container_name: jaeger
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - local-machinedata

  prometheus:
    build: prometheus/.
    container_name: prometheus
    ports:
      - 9090:9090
    networks:
      - local-machinedata
    depends_on:
      - machinedataapi

  grafana:
    build: grafana/.
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - local-machinedata
    volumes:
      - type: volume
        source: grafana-data
        target: /var/lib/grafana
      - type: volume
        source: grafana-data
        target: /var/log/grafana
    depends_on:
      - prometheus

  machinedataapi:
    container_name: machinedataapi
    build: ../.
    ports:
      - 5034:80
      - :80
    environment:
      - ASPNETCORE_ENVIRONMENT=STAGE
      - OTEL_EXPORTER_JAEGER_AGENT_HOST=jaeger
    networks:
      - local-machinedata
    depends_on:
      - postgres
      - jaeger

  # telnetclient:
  #   container_name: nginx
  #   build: nginx/.
  #   ports:
  #     - 8080:80
  #   networks:
  #     - local-machinedata
  #   #depends_on:
  #   #  - machinedataapi
